export const NODES_LOADED = 'NODES_LOADED';
export const NODES_REFRESHING = 'NODES_REFRESHING';
export const NODES_REFRESHED = 'NODES_REFRESHED';
export const NODE_SELECTED = 'NODE_SELECTED';
export const NODE_RETRIEVED = 'NODE_RETRIEVED';