export const ROLES_LOADED = 'ROLES_LOADED';
export const ROLES_LOADED_NO_REFRESH = 'ROLES_LOADED_NO_REFRESH';
export const ROLES_REFRESHING = 'ROLES_REFRESHING';
export const ROLES_REFRESHED = 'ROLES_REFRESHED';
